### ISSUE TITLE
My 2 cents

### ISSUE THREAD

**Issue by AQueff** [ivan-paleo/publish-micro-image#1]
Hi Ivan, 
I'm quite new (basically a noob...) to GitHub so, here is what I wrote you in an email, but I wanted to try on GitHub...

je suis en train de lire ton document. MERCI d'avoir écrit ça !! Je passe mon temps à dire aux gens d'arrêter avec les grossissement et d ene travailler qu'avec les barres d'échelle. Là, j'ai maintenant un super document à leur partager!

Quelques remarques/questions :

en français j'entends les vendeurs de microscope faire la distinction entre grossissement (magnification en anglais) et grandissement (xxxx en anglais). J'allais dire que c'est utile car ça permet de différencier le vrai grossissement "optique" du grossissement visible sur un écran, mais... en fait... pendant que j'écris ce texte... je me dis que non c'est débile car en fait comme tu l'as écris, le grossissement c'est combien de fois mon champs de vue est plus grand sur mon écran que en réalité, donc que ce soit un grandissement numérique rajouté dessus, ben... ça rentre quand même dans la définition de magnification... Mais quand même, peut-être faut-il parler de ça dans ton document (?), si un tel mot existe en anglais pour différencier un peu le pur grossissement optique du grossissement optique+numérique. Est-ce que c'est ce que tu décris comme digital magnification ? On aurait alors grossissement = optical magnification et grandissement = digital magnification ?

Dans la section "Relationship between optical and digital lateral resolutions":

1) second paragraphe, je cite : "The Nyquist criterion (based on Nyquist–Shannon sampling theorem) states that the digital lateral resolution should be 2-3 $\times$ smaller than the optical lateral resolution.". a) un petit souci avec le $\time$ et surtout b) ici tu veux dire que la résolution doit être meilleure j'imagine. Car juste au dessus tu dis que tu ne vas pas utiliser smaller/larger mais better/worse. Mais là, j'imagine, comme c'est une citation, tu peux pas changer. Est-ce que tu peux ajouter dans la citation, entre crochets: [better] ?

2) idem troisième et quatrième paragraphe, tu ré-utilises smaller alors que tu as dit que tu utiliserais better! :))

3) ce troisième paragraphe, je le note là mais peut-être que tu en parles après : tous les fournisseurs de microscopes me racontent ça à chaque fois : "non non ça sert à rien d'avoir un caméra 12 MPixels Alain car la résolution optique blablabla" et bim, ils vendent leur caméra 3 MPixels à 2000€... et quand on met un boîtier d'appareil photo à 300€, ben, les photos, elles sont bien meilleures! Alors, c'est quoi le souci? Leurs capteurs de caméra sont pourris?

Dans la section "Optical vertical resolution and depth of field" : je le note là au cas où j'oublie après : est-ce possible d'indiquer quand même que le processing permet d'améliorer la résolutione n Z du microscope confocal avec cette histoire de courbe de umière par pixel? Je sais pas si tu en parles après... C'est ça que tu voudrais mettre dans la section "Digital vertical resolution" ? On doit pouvoir demander aux types de Sensofar de nous expliquer ça non?

Processing : even the chipset of the camera process the image. Even a RAW image from Canon is specific to Canon, and a RAW image of Nikon is different. The hardware makes a first process.

Saving / Raw vs. derived data: a typo in "distinguish" in the second paragraph.

**Comment by ivan-paleo** [comment]
Thank you @AQueff for your comments and for creating the first issue!

As far as I could find, it seems that there is no distinction in English between "grossissement" and "(a)grandissement": they are both grouped under the term "magnification". But indeed, this is why I try to differentiate with optical and digital magnifications, respectively. If someone has better terms, please [contribute](https://github.com/ivan-paleo/publish-micro-image#how-to-contribute)!

I have also wondered why the cameras sold together with the microscopes are of such low quality compared to DSLR cameras in general. It is not due to the number of pixels for sure, so I guess it has to do with the quality of the sensors (noise level, spectral sensitivity, quantum efficiency, dynamic range...). I don't know much on that, but I can guess that there are some trade-offs between properties. Here again, [contributions](https://github.com/ivan-paleo/publish-micro-image#how-to-contribute) are welcome!

Your other comments have been addressed in commit b4338661329a84fc2f0258e3352883f30696e01d, although I couldn't find any issue with `\times` (comment 1a).
